on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: bookdown

jobs:
  compile:
    runs-on: ubuntu-latest
    container: bioconductor/bioconductor_docker:devel

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      CRAN: ${{ matrix.config.cran }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Installing rebook
        run: |
          BiocManager::install("rebook")
        shell: Rscript {0}

      - name: Update DESCRIPTION
        run: |
            rebook::updateDependencies(".")
        shell: Rscript {0}

      - name: Committing updates to master
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add DESCRIPTION
          git commit -m "Rebuilding sundries." || true
          git push

      - name: Set up pandoc
        uses: r-lib/actions/setup-pandoc@master

      - name: Install remotes
        run: |
          install.packages('remotes')
        shell: Rscript {0}

      - name: Query dependencies
        run: |
          saveRDS(remotes::dev_package_deps(dependencies = TRUE, repos = c(getOption('repos'), BiocManager::repositories())), 'depends.Rds', version = 2)
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: aaron-wuz-here
          key: ${{ runner.os }}-${{ hashFiles('depends.Rds') }}
          restore-keys: ${{ runner.os }}-

      - name: Setup TinyTeX
        uses: r-lib/actions/setup-tinytex@v1

      - name: Install dependencies
        run: |
          local_deps <- remotes::local_package_deps(dependencies = TRUE)
          deps <- remotes::dev_package_deps(dependencies = TRUE, repos = BiocManager::repositories())
          BiocManager::install(local_deps[local_deps %in% deps$package[deps$diff != 0]], Ncpu = 2L)
        shell: Rscript {0}

      - name: Session info
        run: |
          options(width = 100)
          pkgs <- installed.packages()[, "Package"]
          sessioninfo::session_info(pkgs, include_base = TRUE)
        shell: Rscript {0}

      - name: Render book (git)
        run: |
          bookdown::render_book('index.Rmd', 'bookdown::gitbook')
        shell: Rscript {0}

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: _book
